### ISSUE TITLE
这个附魔可以附魔在别的东西上

### ISSUE THREAD

**Issue by layue13** [ClaymanTwinkle/FlySword#4]
是特性(Bug)吗？

**Comment by layue13** [comment]
XD
![image](https://user-images.githubusercontent.com/54186311/63187609-e4078600-c091-11e9-8ab0-9fc311a68b96.png)

**Comment by layue13** [comment]
希望能把方块的朝向改一下
item这里一类按照剑一样
物品正常方向XD

**Comment by layue13** [comment]
希望你能看到

**Comment by ClaymanTwinkle** [comment]
收到

**Comment by Abo233** [comment]
其实，这个完全可以解决，建议楼主加附魔控制mod，可以设置附魔在那个位置，任意武器

**Comment by ClaymanTwinkle** [comment]
是创造模式才会这样，生存就不能附魔。就像原版附魔也是这样，算是这个游戏的一个bug吧。我看了下代码，好像阻止不了创造模式这么做。
